/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dev": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DevController_echo_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Retrieves the profile of the currently authenticated user based on the Clerk authentication token.
         */
        get: operations["UserController_currentUser_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by ID
         * @description Fetches a single user record from the database by its unique identifier.
         */
        get: operations["UserController_findById_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all users
         * @description Retrieves a list of users from the database with an optional limit constraint.
         */
        get: operations["UserController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClerkWebhookController_handleWebhook_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/direct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find or create direct room
         * @description Finds an existing 1-on-1 direct chat with a user or creates a new one.
         */
        post: operations["RoomController_findOrCreateDirect_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find room by ID for current user
         * @description Fetches details of a specific room if the user is a participant.
         */
        get: operations["RoomController_findById_v1"];
        put?: never;
        post?: never;
        /**
         * Delete room
         * @description Permanently deletes a room and all its messages. For GROUP rooms, only the OWNER can delete; for DIRECT rooms, either member can delete.
         */
        delete: operations["RoomController_delete_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all rooms for current user
         * @description Retrieves a list of all rooms (direct and group) that the current user belongs to.
         */
        get: operations["RoomController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create group room
         * @description Creates a new group room with the current user as OWNER and the specified members added to the group.
         */
        post: operations["GroupRoomController_findOrCreateGroup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/group/{roomId}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update group room name
         * @description Updates the name of a specific group room. Requires ADMIN or higher (Owner) role and that the user is a member of the group.
         */
        patch: operations["GroupRoomController_updateName_v1"];
        trace?: never;
    };
    "/api/v1/room/group/{roomId}/add/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GroupRoomController_addNewMember_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/group/{roomId}/avatar/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate presigned signature for group avatar upload
         * @description Step 1 of 3 in the direct upload flow (presigned Cloudinary upload).
         *
         *     📖 **Full frontend integration guide**: [avatar-upload-integration.md](https://github.com/KirillPitomets/infinite-chat/tree/migrate-elysia-to-nest/apps/api/docs/guides/avatar-upload-integration.md)
         *
         *     ⚠️ Step 2 (file upload) goes directly to Cloudinary, not through our backend.
         */
        post: operations["GroupRoomController_presignAvatar_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/group/{roomId}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update group room avatar image
         * @description Step 3 of 3 in the direct upload flow (presigned Cloudinary upload).
         *
         *     Saves the avatar reference (secure URL + public ID) after the client has already uploaded the file directly to Cloudinary using the presigned signature from step 1. This endpoint does **not** receive the file itself — only the resulting metadata.
         *
         *     📖 **Full frontend integration guide**: [avatar-upload-integration.md](https://github.com/KirillPitomets/infinite-chat/tree/migrate-elysia-to-nest/apps/api/docs/guides/avatar-upload-integration.md)
         *
         *     ⚠️ Requires ADMIN or higher role. `avatarUrl` is validated against the Cloudinary domain to prevent arbitrary URL injection.
         */
        patch: operations["GroupRoomController_updateAvatar_v1"];
        trace?: never;
    };
    "/api/v1/room/group/{roomId}/kick/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Kick a member from the group room
         * @description Removes a specific user from the room membership list. Requires ADMIN or higher role. Cannot kick yourself or the room owner.
         */
        delete: operations["GroupRoomController_kickMember_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/group/leave/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Leave a room
         * @description Allows the current user to leave a specific room by removing their membership Group owners cannot leave their groups directly.
         */
        delete: operations["GroupRoomController_leave_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/message/history/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get room message history
         * @description Retrieves a paginated list of chat messages for a specific room. The user must be a member of the room.
         */
        get: operations["MessagesController_getHistory_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/message/attachments/presign/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate presigned attachment upload URLs
         * @description Generates Cloudinary presigned upload URLs for uploading message attachments directly from the client.
         */
        post: operations["MessagesController_presignAttachments_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserEntity: {
            /**
             * @description Unique identifier of the user (UUID)
             * @example 070145d6-2ba3-4588-b911-7e168e6d4880
             */
            id: string;
            /**
             * @description First name of the user
             * @example John
             */
            firstName: string;
            /**
             * @description Last name of the user
             * @example Doe
             */
            lastName: string;
            /**
             * @description Unique username
             * @example john_dev
             */
            username: string;
            /**
             * @description Primary email address of the user
             * @example john@example.com
             */
            email: string;
            /**
             * @description URL of the user profile avatar
             * @example https://img.clerk.com/xxx.jpg
             */
            imageUrl: string;
            /**
             * Format: date-time
             * @description Timestamp when the user was last active
             * @example 2026-07-29T10:00:00.000Z
             */
            lastSeen: string;
            /**
             * Format: date-time
             * @description Timestamp when the user account was created
             * @example 2026-01-15T08:30:00.000Z
             */
            createdAt: string;
        };
        ErrResponse: {
            /** @example 404 */
            statusCode: number;
            /** @example User not found */
            message: string | string[];
            /** @example Not Found */
            error: string;
        };
        FindOrCreateDirectRoomDto: {
            /**
             * Format: uuid
             * @description ID of the target user to start a direct chat with (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            memberId: string;
        };
        RoomMemberEntity: {
            /**
             * Format: uuid
             * @description Unique identifier of the room membership (UUID)
             * @example b1f486a9-8f92-4c6e-93b1-2e64b8a2c3d4
             */
            id: string;
            /**
             * Format: date-time
             * @description Date and time when the user last read messages in this room
             * @example 2026-07-30T10:15:00.000Z
             */
            lastReadAt: string | null;
            /**
             * @description Role of the member within the room
             * @example MEMBER
             * @enum {string}
             */
            role: "OWNER" | "ADMIN" | "MEMBER";
            /** @description Detailed profile information of the member user */
            user: components["schemas"]["UserEntity"];
        };
        RoomEntity: {
            /**
             * @description Unique identifier of the room (UUID)
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            id: string;
            /**
             * @description Name of the room
             * @example Cozy Living Room
             */
            name: string;
            /**
             * @description Type of the room
             * @example DIRECT
             * @enum {string}
             */
            type: "DIRECT" | "GROUP";
            /**
             * @description URL of the room image
             * @example https://example.com/images/room1.jpg
             */
            avatarUrl: string;
            /** @description Id of the room image */
            avatarPublicId: string;
            /** @description memberships list */
            memberships: components["schemas"]["RoomMemberEntity"][];
            /**
             * @description ID of the user who created the room
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            createdByUserId: string;
            /**
             * Format: date-time
             * @description Date and time when the room was created
             * @example 2026-07-30T07:04:18.000Z
             */
            createdAt: string;
        };
        CreateGroupRoomDto: {
            /**
             * @description Array of user IDs to include in the group (UUIDs)
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000",
             *       "987e6543-e21b-12d3-a456-426614174999"
             *     ]
             */
            memberIds: string[];
            /**
             * @description Name of the group chat
             * @example Project Team Chat
             */
            name: string;
        };
        UpdateGroupNameDto: {
            /**
             * @description Name of the group chat
             * @example Project Team Chat
             */
            name: string;
        };
        PresignedUrlEntity: {
            /**
             * @description Cryptographic signature for authenticating the direct upload request
             * @example a1b2c3d4e5f67890123456789abcdef012345678
             */
            signature: string;
            /**
             * @description Timestamp when the signature was generated
             * @example 1718712345
             */
            timestamp: string;
            /**
             * @description Target folder in cloud storage where the file will be uploaded
             * @example groups/{roomId}/avatar
             */
            folder: string;
            /**
             * @description Generated public identifier (name) for the uploaded file
             * @example room_a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11_1718712345
             */
            publicId: string;
            /**
             * @description Cloudinary API key associated with the account
             * @example 123456789012345
             */
            apiKey: string;
            /**
             * @description Cloud storage cloud name
             * @example my-cloud-name
             */
            cloudName: string;
        };
        UpdateGroupAvatarDto: {
            /**
             * @description URL of the group chat avatar
             * @example https://example.com/images/group.jpg
             */
            url: string;
            /**
             * @description Id of the group chat avatar
             * @example groups/{roomId}/avatar
             */
            publicId: string;
        };
        MessageAttachmentEntity: {
            /**
             * @description Unique attachment identifier (uuid)
             * @example a1b2c3d4-e5f6-7890-1234-56789abcdef0
             */
            id: string;
            /**
             * @description Storage key/filename in the cloud storage (e.g., Cloudinary/S3)
             * @example uploads/messages/att_12345.png
             */
            key: string;
            /**
             * @description Original file name
             * @example document.pdf
             */
            name: string;
            /**
             * @description Direct public URL of the uploaded attachment
             * @example https://res.cloudinary.com/demo/image/upload/v1/sample.jpg
             */
            url: string;
            /**
             * @description File size in bytes
             * @example 1048576
             */
            size: number;
            /**
             * @description Type of attachment (e.g., IMAGE, FILE, AUDIO, VIDEO)
             * @example IMAGE
             * @enum {string}
             */
            type: "VIDEO" | "IMAGE" | "AUDIO" | "FILE";
            /**
             * Format: date-time
             * @description Timestamp when the attachment was created
             * @example 2026-03-30T12:00:00.000Z
             */
            createdAt: string;
        };
        ReplyMessageEntity: {
            /**
             * @description Unique ID of the referenced message being replied to
             * @example d8c2b7e1-8f4b-4b2a-9e1d-3c8f5a6b7c8d
             */
            id: string;
            /**
             * @description Text content of the replied message
             * @example Original message text
             */
            text?: string | null;
            /**
             * @description Flag indicating whether the replied message was deleted
             * @example false
             */
            isDeleted: boolean;
            /** @description Author of the replied message */
            sender: components["schemas"]["UserEntity"];
            /** @description List of attachments in the replied message */
            attachments: components["schemas"]["MessageAttachmentEntity"][];
            /**
             * Format: date-time
             * @description Timestamp when the original message was created
             * @example 2026-03-30T11:55:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the original message was last updated
             * @example 2026-03-30T11:55:00.000Z
             */
            updatedAt: string;
        };
        MessageEntity: {
            /**
             * @description Unique message identifier (uuid)
             * @example d8c2b7e1-8f4b-4b2a-9e1d-3c8f5a6b7c8d
             */
            id: string;
            /**
             * @description Unique room identifier (uuid)
             * @example d8c2b7e1-8f4b-4b2a-9e1d-3c8f5a6b7c8d
             */
            roomId: string;
            /**
             * @description Text content of the message. Nullable for attachment-only messages.
             * @example Hello! Check out this document.
             */
            text?: string | null;
            /** @description User who sent the message */
            sender: components["schemas"]["UserEntity"];
            /** @description Parent message being replied to, if applicable */
            replyToMessage?: components["schemas"]["ReplyMessageEntity"] | null;
            /** @description List of files or media attached to the message */
            attachments: components["schemas"]["MessageAttachmentEntity"][];
            /**
             * @description Type of the message
             * @example USER
             * @enum {string}
             */
            type: "USER" | "SYSTEM";
            /**
             * @description Arbitrary JSON metadata associated with the message
             * @example {
             *       "key": "value"
             *     }
             */
            metadata?: Record<string, never> | null;
            /**
             * @description System-generated text/content for system events (e.g. user joined)
             * @example User joined the room
             */
            systemContent?: string | null;
            /**
             * @description Flag indicating whether the message has been soft-deleted
             * @example false
             */
            isDeleted: boolean;
            /**
             * Format: date-time
             * @description Timestamp when the message was created
             * @example 2026-03-30T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the message was last updated
             * @example 2026-03-30T12:00:00.000Z
             */
            updatedAt: string;
        };
        CreateMessageAttachmentDto: {
            /**
             * @description Name of the attachment file
             * @example document
             */
            name: string;
            /**
             * @description Storage key or unique path identifier for the file
             * @example uploads/attachments/document_uuid.pdf
             */
            key: string;
            /**
             * @description Type of the message attachment
             * @example IMAGE
             * @enum {string}
             */
            type: "VIDEO" | "IMAGE" | "AUDIO" | "FILE";
            /**
             * @description File size in bytes (maximum 20MB / 20971520 bytes)
             * @example 1048576
             */
            size: number;
            /**
             * @description Public URL of the attachment file
             * @example https://storage.example.com/uploads/document.pdf
             */
            url: string;
        };
        CreateMessageDto: {
            /**
             * Format: uuid
             * @description Unique room identifier where the message is sent (UUID v4)
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            roomId: string;
            /**
             * @description Text content of the message (max 160 characters)
             * @example Hello, team!
             */
            text?: string | null;
            /**
             * Format: uuid
             * @description Identifier of the message being replied to (UUID v7)
             * @example 018f3b2c-8a1a-7b2c-8d3e-4f5a6b7c8d9e
             */
            replyToMessageId?: string | null;
            /** @description List of attachments included in the message */
            attachments?: components["schemas"]["CreateMessageAttachmentDto"][] | null;
        };
        UpdateMessageDto: {
            /**
             * Format: uuid
             * @description Unique room identifier where the message is sent (UUID v4)
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            roomId: string;
            /**
             * @description Text content of the message (max 160 characters)
             * @example Hello, team!
             */
            text?: string | null;
            /**
             * Format: uuid
             * @description Identifier of the message being replied to (UUID v7)
             * @example 018f3b2c-8a1a-7b2c-8d3e-4f5a6b7c8d9e
             */
            replyToMessageId?: string | null;
            /** @description List of attachments included in the message */
            attachments?: components["schemas"]["CreateMessageAttachmentDto"][] | null;
            /**
             * Format: uuid
             * @description Unique identifier of the message being updated (UUID v7)
             * @example 018f3b2c-8a1a-7b2c-8d3e-4f5a6b7c8d9e
             */
            messageId: string;
        };
        DeleteMessageDto: {
            /**
             * Format: uuid
             * @description Unique room identifier (UUID v4)
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            roomId: string;
            /**
             * Format: uuid
             * @description Unique message identifier to delete (UUID v7)
             * @example 018f3b2c-8a1a-7b2c-8d3e-4f5a6b7c8d9e
             */
            messageId: string;
        };
        RestoreMessageDto: {
            /**
             * Format: uuid
             * @description Unique room identifier (UUID v4)
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            roomId: string;
            /**
             * Format: uuid
             * @description Unique message identifier to restore (UUID v7)
             * @example 018f3b2c-8a1a-7b2c-8d3e-4f5a6b7c8d9e
             */
            messageId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    DevController_echo_v1: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_currentUser_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
            /** @description User is not authenticated (missing or invalid Clerk token) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User profile with the specified Clerk ID was not found in the database */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    UserController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique user identifier (uuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
            /** @description User with the specified ID was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    UserController_findAll_v1: {
        parameters: {
            query?: {
                /** @description Maximum number of users to fetch */
                limit?: number;
                /** @description Number of page */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"][];
                };
            };
        };
    };
    ClerkWebhookController_handleWebhook_v1: {
        parameters: {
            query?: never;
            header: {
                "svix-id": string;
                "svix-timestamp": string;
                "svix-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoomController_findOrCreateDirect_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindOrCreateDirectRoomDto"];
            };
        };
        responses: {
            /** @description Direct room successfully retrieved or created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomEntity"];
                };
            };
            /** @description Attempted to create a chat with yourself or invalid user ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    RoomController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique room identifier (UUID) */
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room details successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomEntity"];
                };
            };
            /** @description Room with the specified ID was not found or user is not a member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    RoomController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique room identifier (UUID) */
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not the owner of this GROUP room */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description Room not found, or user is not a member of this room */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    RoomController_findAll_v1: {
        parameters: {
            query?: {
                /** @description Number of records to return */
                limit?: number;
                /** @description Number of page */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of rooms successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomEntity"][];
                };
            };
        };
    };
    GroupRoomController_findOrCreateGroup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRoomDto"];
            };
        };
        responses: {
            /** @description Group room successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomEntity"];
                };
            };
            /** @description The creator ID is included in memberIds, or one or more provided member IDs do not exist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    GroupRoomController_updateName_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique room identifier (UUID) */
                roomId: string;
            };
            cookie?: never;
        };
        /** @description New name for the group room */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupNameDto"];
            };
        };
        responses: {
            /** @description Group room name successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomEntity"];
                };
            };
            /**
             * @description roomId param is missing from the request
             *
             *     Invalid input data or validation failed
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not authenticated (missing Clerk ID) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not a member of this room, or lacks the required role (ADMIN or higher). Not enforced for DIRECT rooms. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description Group room with the specified ID was not found, type is not GROUP, or user is not a member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    GroupRoomController_addNewMember_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupRoomController_presignAvatar_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique room identifier (UUID) */
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned upload credentials successfully generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlEntity"];
                };
            };
            /** @description roomId param is missing from the request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not authenticated (missing Clerk ID) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not a member of this room, or lacks the required role (ADMIN or higher). Not enforced for DIRECT rooms. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description Group room with the specified ID was not found or user is not a member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    GroupRoomController_updateAvatar_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique room identifier (UUID) */
                roomId: string;
            };
            cookie?: never;
        };
        /** @description Avatar URL and public ID returned by Cloudinary after upload (step 2) */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupAvatarDto"];
            };
        };
        responses: {
            /** @description Group room avatar successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomEntity"];
                };
            };
            /**
             * @description roomId param is missing from the request
             *
             *     Invalid input data, validation failed, avatarUrl does not match the expected Cloudinary domain
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not authenticated (missing Clerk ID) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not a member of this room, or lacks the required role (ADMIN or higher). Not enforced for DIRECT rooms. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description Group room with the specified ID was not found or user is not a member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    GroupRoomController_kickMember_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique room identifier (UUID) */
                roomId: string;
                /** @description Unique user identifier of the member to kick (UUID) */
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member successfully removed from the room */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /**
             * @description roomId param is missing from the request
             *
             *     roomId/memberId param is missing, attempted to kick yourself, or attempted to kick the room owner
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not authenticated (missing Clerk ID) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is not a member of this room, or lacks the required role (ADMIN or higher). Not enforced for DIRECT rooms. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description Group room was not found, or the specified member is not in the room */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    GroupRoomController_leave_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique room identifier (UUID) */
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully left the room */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description User is the group owner and cannot leave without transferring ownership first, or the room is a DIRECT chat (leaving is not supported for direct messages) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
            /** @description Room not found or user is not in this room */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrResponse"];
                };
            };
        };
    };
    MessagesController_getHistory_v1: {
        parameters: {
            query?: {
                /** @description Number of records to return */
                limit?: number;
                /** @description Number of page */
                page?: number;
            };
            header?: never;
            path: {
                /** @description Unique room identifier (uuid) */
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of room messages successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageEntity"][];
                };
            };
            /** @description User is not authenticated (missing or invalid Clerk token) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access denied (user is not a member of the room) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User profile with the specified Clerk ID was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MessagesController_presignAttachments_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique room identifier (uuid) */
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned upload URLs generated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlEntity"];
                };
            };
            /** @description User is not authenticated (missing or invalid Clerk token) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User profile with the specified Clerk ID was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
