import {authClient} from "@/lib/auth/client"
import {NeonAuthUIProvider} from "@neondatabase/auth/react"

import type {Metadata} from "next"
import {Noto_Sans} from "next/font/google"
import "./globals.css"

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Infinite Chat",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>
        <NeonAuthUIProvider authClient={authClient} emailOTP>
          {children}
        </NeonAuthUIProvider>
      </body>
    </html>
  )
}
