import { Providers } from "@/shared/providers"
import type { Metadata } from "next"
import { Noto_Sans } from "next/font/google"
import Script from "next/script"
import "./globals.css"

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Infinite Chat",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Script src="http://localhost:8097" />
      <body className={`${notoSans.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
