export const chats = [
  {
    name: "John Doe",
    photo: "https://randomuser.me/api/portraits/men/11.jpg",
    lastMessage: "How are you?",
    messageCreatedAt: "2021-12-30, 16:23",
    status: "online",
  },
  {
    name: "Kate Wilson",
    photo: "https://randomuser.me/api/portraits/women/21.jpg",
    lastMessage: "See you tomorrow!",
    messageCreatedAt: "2021-12-30, 15:58",
    status: "offline",
  },
  {
    name: "Alex Brown",
    photo: "https://randomuser.me/api/portraits/men/32.jpg",
    lastMessage: "Got it 👍",
    messageCreatedAt: "2021-12-30, 15:40",
    status: "online",
  },
  {
    name: "Emily Clark",
    photo: "https://randomuser.me/api/portraits/women/45.jpg",
    lastMessage: "Can you send the files?",
    messageCreatedAt: "2021-12-30, 15:22",
    status: "offline",
  },
  {
    name: "Michael Scott",
    photo: "https://randomuser.me/api/portraits/men/54.jpg",
    lastMessage: "That's what she said 😄",
    messageCreatedAt: "2021-12-30, 15:10",
    status: "online",
  },
  {
    name: "Sarah Johnson",
    photo: "https://randomuser.me/api/portraits/women/60.jpg",
    lastMessage: "Thanks!",
    messageCreatedAt: "2021-12-30, 14:55",
    status: "offline",
  },
  {
    name: "David Miller",
    photo: "https://randomuser.me/api/portraits/men/67.jpg",
    lastMessage: "I'll check it later",
    messageCreatedAt: "2021-12-30, 14:41",
    status: "offline",
  },
  {
    name: "Olivia Smith",
    photo: "https://randomuser.me/api/portraits/women/72.jpg",
    lastMessage: "Sounds good 👌",
    messageCreatedAt: "2021-12-30, 14:30",
    status: "online",
  },
  {
    name: "Chris Evans",
    photo: "https://randomuser.me/api/portraits/men/81.jpg",
    lastMessage: "Let's do it",
    messageCreatedAt: "2021-12-30, 14:18",
    status: "offline",
  },
  {
    name: "Anna Taylor",
    photo: "https://randomuser.me/api/portraits/women/88.jpg",
    lastMessage: "I'm on my way",
    messageCreatedAt: "2021-12-30, 14:05",
    status: "online",
  },
  {
    name: "Robert King",
    photo: "https://randomuser.me/api/portraits/men/93.jpg",
    lastMessage: "Perfect",
    messageCreatedAt: "2021-12-30, 13:52",
    status: "offline",
  },
  {
    name: "Sophia Martinez",
    photo: "https://randomuser.me/api/portraits/women/95.jpg",
    lastMessage: "Can we reschedule?",
    messageCreatedAt: "2021-12-30, 13:40",
    status: "offline",
  },
  {
    name: "Daniel Lee",
    photo: "https://randomuser.me/api/portraits/men/98.jpg",
    lastMessage: "No problem",
    messageCreatedAt: "2021-12-30, 13:28",
    status: "online",
  },
  {
    name: "Emma Davis",
    photo: "https://randomuser.me/api/portraits/women/12.jpg",
    lastMessage: "Haha 😅",
    messageCreatedAt: "2021-12-30, 13:15",
    status: "online",
  },
  {
    name: "James Anderson",
    photo: "https://randomuser.me/api/portraits/men/17.jpg",
    lastMessage: "I'll call you later",
    messageCreatedAt: "2021-12-30, 13:02",
    status: "offline",
  },
];
